[panel_meta]
name = "Test layout :3"
default_size = [512, 256]
min_size = [512, 256]
max_size = [99999, 99999]
bg_color = [0.1, 0.1, 0.2, 1.0]

[elements.test_label1]
type = "text"
panel_anchor = "top left"
top_left = [16, 16]
bottom_right = [128, 128]
depth = 0.1
text = "test1 yippee"
text_scale = 2.0
text_color = [0.0, 1.0, 1.0, 1.0]
text_ui_anchor = "top left"
text_text_anchor = "top left"

[elements.test_label2]
type = "text"
panel_anchor = "bottom right"
top_left = [-128, -128]
bottom_right = [-16, -16]
depth = 0.1
text = "test2 yippee"
text_scale = 1.0
text_color = [1.0, 0.0, 0.0, 1.0]
text_ui_anchor = "bottom right"
text_text_anchor = "bottom right"
