[panel_meta]
title = "Track"
default_size = [720, 320]
min_size = [720, 320]
max_size = [720, 320]
bg_color = [0.1, 0.1, 0.2, 1.0]

# MIDI port selector
[elements.midi_port_numberbox]
type = "numberbox"
panel_anchor = "top left"
top_left = [12, 12]
bottom_right = [76, 76]
color_inner = [1.0, 1.0, 0.0, 0.0]
color_outer = [1.0, 1.0, 0.0, 1.0]
thickness = 2.0
min = 0.0
max = 127.0
step = 1.0
step_fine = 1.0
default_value = 1.0
visual_decimal_places = 0
variable = "midi_port"

# MIDI port selector
[elements.wave_type_combobox]
type = "combobox"
panel_anchor = "top left"
top_left = [78, 16]
bottom_right = [708, 76]
depth = 0.1
entries = ["(no devices found)"]
item_height = 40.0
list_height = 200.0
default_index = 0
variable = "midi_port"

# DEBUG TEXT
[elements.debug_text]
type = "text"
panel_anchor = "top left"
top_left = [12, 88]
bottom_right = [708, 308]
depth = 0.1
text = "qwertyuiop"
text_scale = [2.0, 2.0]
text_color = [0.0, 1.0, 1.0, 1.0]
text_ui_anchor = "top left"
text_text_anchor = "top left"

# PIN
[elements.midi_out_pin]
type = "pin"
pin_type = "midi"
pin_direction = "output"
pin_name = "midi_out"
pin_position_y = 24.0
