name: Formatting
on: push

jobs:
  check-formatting:
    name: Ensure correct code formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: clang-format Check
        uses: jidicula/clang-format-action@v4.15.0
        with:
          clang-format-version: '16'
          check-path: '.'
